type User {
    _id: ID
    name: String!
    email: String!
    password: String!
    devices: [Device]!
}

type Device {
    _id: ID
    tel: String!
    privateKey: String!
    locations: [Location]!
}

type Location {
    _id: ID
    longitude: String!
    latitude: String!
}

type Authentication {
    userId: ID!
    token: String!
    tokenExpiration: String!
}

input LocationInput {
    longitude: String!
    latitude: String!
}

input UserInput {
    name: String!
    email: String!
    password: String!
}

input LoginInput {
    email: String!
    password: String!
}

input DeviceInput {
    tel: String!
}

type RootMutation {
    createLocation(locationInput: LocationInput!) : Location
    createUser(userInput: UserInput!) : User
    createDevice(deviceInput: DeviceInput!) : Device
}

type RootQuery {
    locations: [Location!]!
    users: [User!]!
    user: User!
    devices: [Device!]!
    login(loginInput: LoginInput!) : Authentication! 
}

schema {
    query: RootQuery
    mutation: RootMutation
}